name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: scp -o StrictHostKeyChecking=no index.html ubuntu@your-ec2-public-dns:/tmp/

      - name: Run Ansible Playbook
        run: ansible-playbook -i your-ec2-public-dns, deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
